# Generated by Django 5.1.6 on 2025-02-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体重(kg)')),
                ('systolic_pressure', models.IntegerField(verbose_name='收缩压(mmHg)')),
                ('diastolic_pressure', models.IntegerField(verbose_name='舒张压(mmHg)')),
                ('heart_rate', models.IntegerField(verbose_name='心率(次/分钟)')),
                ('record_time', models.DateTimeField(verbose_name='记录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '健康记录',
                'verbose_name_plural': '健康记录',
                'ordering': ['-record_time'],
            },
        ),
    ]
