# Generated by Django 5.1.6 on 2025-03-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='blood_sugar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='血糖(mmol/L)'),
        ),
    ]
