# Generated by Django 5.1.6 on 2025-03-02 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0002_healthrecord_blood_sugar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['user', 'record_time'], name='health_info_user_id_bc4769_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['record_time'], name='health_info_record__2ec9be_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['user', 'weight'], name='health_info_user_id_9d1a81_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['user', 'systolic_pressure', 'diastolic_pressure'], name='health_info_user_id_fc38ec_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['user', 'heart_rate'], name='health_info_user_id_edb848_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['user', 'blood_sugar'], name='health_info_user_id_15308e_idx'),
        ),
    ]
