# Generated by Django 5.1.6 on 2025-03-11 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_info', '0003_healthrecord_health_info_user_id_bc4769_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('weight', '体重'), ('blood_pressure', '血压'), ('blood_sugar', '血糖'), ('medicine', '服药')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('once', '一次性'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月')], max_length=10)),
                ('time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
                'indexes': [models.Index(fields=['user', 'type'], name='health_info_user_id_23ab36_idx'), models.Index(fields=['user', 'is_active'], name='health_info_user_id_ef3151_idx'), models.Index(fields=['user', 'frequency'], name='health_info_user_id_7cc5ca_idx')],
            },
        ),
    ]
