# Generated by Django 5.1.6 on 2025-03-11 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='药物名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='用药说明')),
                ('frequency', models.CharField(choices=[('daily', '每天'), ('weekly', '每周'), ('monthly', '每月'), ('custom', '自定义')], default='daily', max_length=20, verbose_name='服药频率')),
                ('weekdays', models.CharField(blank=True, help_text='用逗号分隔的数字，1-7表示周一至周日', max_length=20, null=True, verbose_name='每周服药日')),
                ('month_days', models.CharField(blank=True, help_text='用逗号分隔的数字，1-31表示每月具体日期', max_length=100, null=True, verbose_name='每月服药日')),
                ('custom_interval', models.PositiveIntegerField(blank=True, help_text='以天为单位的自定义间隔', null=True, verbose_name='自定义间隔天数')),
                ('times', models.CharField(help_text='用逗号分隔的时间字符串，格式为HH:MM', max_length=100, verbose_name='服药时间')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '药物提醒',
                'verbose_name_plural': '药物提醒',
            },
        ),
    ]
